

# 签约

作者和出版商首先要签约，这样才能互相联系．签约的过程，在github上，就体现在建立联系．

## 确定出版商

找到github，确定你要使用它作为出版商．

在github上面注册一个帐号．进入github网址[点击这里进入](https://github.com/), 输入用户名，邮箱及密码注册．

## 建立联系

github会给你一个办公室，用来交稿. 这是一个互动的程序，你也需要告诉github你自己创作的地方，这样就在你和github之间就建立了联系.　这里涉及两个地点，github上的办公室，你的创作地点．术语**仓库**, github上的办公室，叫**远程仓库**, 你的创作地点在你电脑上的文件夹，术语**本地仓库**.

* 建立远程仓库

前面注册过了，登录你的github帐号，点击Repository（仓库），创建一个远程仓库．

* 建立本地仓库
  * 在你的github仓库，点击clone or download，复制你的仓库网络地址．
  * cd到你的文件夹
  
    ```
    # 比如你要去wang这个文件夹
    cd ~/wang/
    # 当然可以直接在图形窗口点击进去，就像windows一样
    ```

  * git clone <仓库网络地址>
  
    ```
    # git clone 和你的github仓库取得联系
    # 你上面复制出来是什么网址，就用那一个
    git clone <你复制的网址>
    ```
  
建立本地仓库的过程，要注意的是，你需要和远程仓库取得联系，你不可能在本地建立一个文件夹就可以和远程仓库去的联系，你必须走一定的程序．一个方法是，在你建立的远程仓库获得仓库地址，在你想作为本地仓库的文件夹下，用git命令创建. git命令会自动给你创建一个.git的文件，用来建立联系．


做完上面的步骤，你应该会在本地仓库里面，有一个.git的文件夹．联系已经建立，开始写作．


可以用remote命令查看你的远程仓库（确认你完成了上面的操作），在用rmote查询后，你会看到一个origin加上网址的两行输出．origin是后面的网址的别名，方便后面输入网址时直接输入origin代替. 

```
git remote -v
```

还有另外一种建立仓库的形式，这中方式和前面相反，先在你的本地电脑建立仓库，再去连接github上的远程仓库．

比如你的本地电脑建立了一个文件夹，叫localrepository的仓库，进入这个文件夹，做一下操作：

```
cd 进localrepository
# 初始化文件夹
git init
```




