

# 写作

写作的大致应该有这样的过程

* 写入文字
  根据自身情况，选择文字编辑器．相当与选择纸张和笔．写入文字后，使用add命令，让git软件跟踪这个文件，并把修改加进来准备提交给远程仓库．一定要把本地电脑的仓库，和github上的仓库做一个区分，这样才能理解为什么使用add命令．你写的文字在你本地的电脑上，通过一定的程序来决定那些文件提交，那些不提交．这和写作有相似之处，你写文章的过程，必然会选择那些文字保留，那些不保留．（git不会主动跟踪文件，需要你下命令，这样做的好处是，在思考不成熟的时候，可以写到一些git不跟踪的文件里面，这样最终成稿不会包含他们）．

```
# 比如你写了一个叫index.html的文件，git跟踪文件变动命令
git add index.html
```

* 修改

  文章千古事，写了文章，修改就是曲中之意．只要前面使用add命令的文件，git会自动跟踪我们作出的修改．

```
# 查询你的文章的状态（未修改，修改，确稿，定稿)
git status
# 确认修改和跟踪的命令是同一个
git add 
```


* 审稿

  审稿是和平时理解不太一样的地方．比如我们写的文章以章为单位，每章是一个文件．我们修改了很多处原稿，但是我们只想让其中的第二章确认修改，其他的修改我们想再斟酌一下，这个时候审稿就很有作用了．选择你需要的修改第二章确稿，没有确认的部分不会出现在你的github文章里面(在你的本地电脑里面，但是还没有确稿）． 

```
# 比如你确认index.html的修改有效, 同前面一样的命令．
git add index.html
# 你可以确认全部修改有效，同时也在这个时候，git开始跟踪你的文件变化
git add .
```


* 定稿

  定稿在gibhub上有很重要的作用．由于是电脑，github能做所谓的照相功能．你从开始写作到最终出版的过程看作一个时间段的话，git可以存你想要保存的时间点，你需要的，可以随时回到当时的状态．可以看作游戏的回放功能，你保存了游戏的话，可以选几个时间点从哪里开始游戏．同时，它也是文章最后的样子，经过定稿，文章从修改到审稿后的效果，就会呈现出来了．
  
```
# 定稿，-m 意思comment, 给一个提示信息，便于你以后找回
git commit -m "修改了index.html文件"
```

> **注意**
> 以上的过程，是一个循环的过程，做好一部分，定稿一部分．不满意，用定稿的照相功能回到你想要的阶段，从新开始．这也是和平时写作概念不一样的地方，手工写作，一般会最后再确认文章的样子，先写文章的内容，而电脑可以随时看到文章的样子.

